version: '3.8'

services:
  web:
    container_name: msu-iit-connect
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_PROJECT_ID: ${VITE_SUPABASE_PROJECT_ID}
        VITE_SUPABASE_PUBLISHABLE_KEY: ${VITE_SUPABASE_PUBLISHABLE_KEY}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
    ports:
      - "8080:80"
    restart: always
